Inclusion of ES6
Kirabo19/Awesome-books pull request #1
Opened 2022-06-08 12:48 UTC by Kirabo19

Re-create  Awesome books app as detailed below :

-     Use ES6 syntax.
-     Divide your code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file.

2022-06-08 13:31 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Kirabo19👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 13:31 UTC, thecodechaser commented on modules/ShowContact.js
> +  const bookList = document.getElementById('books-list');
- [ ] Please change this function to the arrow function to follow ES6 syntax.

2022-06-08 13:31 UTC, thecodechaser commented on modules/addBook.js
> +  form.addEventListener('submit', () => {
- [ ] Please change this function to the arrow function to follow ES6 syntax.

2022-06-08 13:31 UTC, thecodechaser commented on modules/bookList.js
> +  const bookList = document.getElementById('books-list');
- [ ] Please change this function to the arrow function to follow ES6 syntax.

2022-06-08 13:31 UTC, thecodechaser commented on modules/showForm.js
> +  const contact = document.getElementById('contact');
- [ ] Please change this function to the arrow function to follow ES6 syntax.

2022-06-08 13:31 UTC, thecodechaser commented on modules/app.js
> +// addBookToList.addEventListener('click', showBook);
- [ ] Please remove commented code from all of your files, This will make sure that your code looks clean and professional.

2022-06-09 08:14 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🍾🎉**
Hello @Kirabo19 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 08:30 UTC, merged